#+STARTUP: indent

Lensing reconstruction

* What is CMB lensing?
** explain cmb lensing

** cmb lensing and T,E,B modes
* Why lensing reconstruction?
** premordial GW
** dark matter
** delensing
** lensing cross-correlation
* How lensing reconstruction?
** lensing reconstruction
estimators
** lensing reconstruction on cut-sky
** lensing reconstruction on full-sly
*** show work
*** future plan on lensing reconstruction
* bias to cmb lensing reconstruction to reionization ksz
** reionization
** ksz
** explain how reionization ksz affects lensing reconstruction

* appendix


GW, tensor mode, polarization, EB mode
B mode sources
cmb tempature, polarization fields, fourier space, off-diagnal terms
noise model! noise unit!
optical depth
s/n 
* questions
- patchy tau
- optial depth
- reionization and ksz!!!
- lensing potential and convergence
- transfer functions
- matrix degree of freedom
- scales! units!


- cosmological parameters understanding
- lensing effect scale
- lensing effect on TT, TB, EB, order
- ell and angular scale and pixells
- B mode other contributions
- B mode other sources
- vector modes

- large scale, intermediate redshifts
- newlens alm and lensing map


- trispectrum
- reionization ksz affects lensing reconstruction physical image
- bias to lensing reconstruction from reionization ksz: temperature field and polarization field, scale?
- noise, map noise, noise level, N_pix in paperlaptop
- event horizon and gravitationl wave scales
- show results and preliminary conclusion

** 
? how curved sky better than flat sky; compare between them? 
? isotropic? unlensed CMB multipoles are assumed to be Gaussian and statistically isotropic(explain)
? name of l and alm

** 
? code source
? declining geometric kernel of CMB lensing at these high redshifs.

? compton scattering and Thomson scattering: Thomson scattering is the elastic scattering of electromagnetic radiation by a free charged particle, as described by classical electromagnetism. It is the low-energy limit of Compton scattering: the particle's kinetic energy and photon frequency do not change as a result of the scattering. This limit is valid as long as the photon energy is much smaller than the mass energy of the particle: , or equivalently, if the wavelength of the light is much greater than the Compton wavelength of the particle.

Reionization: At a redshift of about 10, hydrogen gets ionized again by the ultraviolet radiation of the first structures
kSZ: 



tSZ effect: CMB photons interact with electrons that have high energies due to their temperature
kSZ effect 
kSZ anisotropies: are produced in cosmological epochs during which there are large fluctuations in the electron density. ? (physical image)
``kSZ'' is used to refer to any blackbody temperature fluctuation arising from bulk motion integrated along the line of sight, including the Doppler effect.

? We refer to the Doppler effect as responsible for large-angle kSZ anisotropies.
? bulk velocity
? patchy reionization
? (B+C+E)
** 
To lowest order (in both optical depth and velocity), the kSZ effect produced only temperature anisotropies, not polarization anisotropies. 

late-time kSZ: are present in galaxies and clusters due to the non-linear growth of structure
reionization kSZ: fluctuations in the electron density field are due to fluctuations in the ionization fraction, are also expected to be correlated with the matter density field and hence with CMB lensing. 

? non-linear growth of structure
? seperation of ``late-time'' ksz and ``reionization ksz''
? addition of ``reionization ksz'' map and ``temperature'' map
? how do I tell the difference between ``late-time'' kSZ and ``reionization'' kSZ?

? model of reionization kSZ
? CMB unlensed and lensed simulations
? websky reionization kSZ simulation and late-time kSZ(Dr.Trac might ask about this)

CMB-S3 and CMB-S4 lensing 
for a Stage 4 CMB experiment
Their results have neglected the kSZ signal from reionization. 
kSZ sigunal due to fluctuations in the ionization fraction during reionization can bring a detectable bias(squeezed limit trispectrum)
I am working on simulating the bias to lensing reconstruction from reionization kSZ effect. 


As a member of both the Atacama Cosmology Telescope (ACT) and the
Simons Observatory (SO), I am actively involved in the research and
analysis projects in the collaborations. A short summary of each of my
involvements is listed below.

** 
Future:
So my work is mainly around lensing reconstruction.

1.Studying the bias to polarization reconstruction.
2.Primordial non-Gaussianity, collaborate with Yilun.

* tips
physical image!
search key words
order of magnitude!
report
make sure to understand every teminology in the report
show simulations
plans
* words
This applies to the simulated temperature full-sky map by now. My next setp would be improving its performance and applying polarization maps and then considering patchy maps.
* committe meeting
- lensing
- future plan related to lensing?
- full-sky and flat-sky comparison
- lensing reconstruction
** what?
** why?
** B mode topic
premodial B mode and tensor mode
** scalar-vector-tensor mode decomposition
** gravitational waves
** quadrupole and premordial B mode
** Q,U and E,B picture
- lecture notes in cosmology
- search E-mode and B-mode
- search stokes parameters and E-mode,B-mode in the "lectures notes in cosmology"
** 
* sources 
- yilun's committee meeting report
* report
* Arthur
show lensing maps, ksz maps
explain ksz simulations
add figures in the report
ksz lensing effect limit
* lecture
1.E B mode image
2.cosmological parameters constraints
3.real experiment, unlensed powerspec

(p1) Hello, My name is Hongbo Cai. I am Dr.Kosowsky's student. This is my first committee meeting. Thank you for being a part of my committee and attending today's meeting. 

(p2) I will give an introduction of my research. There are two parts of my work: the first one is CMB lensing reconstruction on the curved sky; the second one is bias to lensing reconstruction from temperature anisotropies dut to reionization kSZ effect.

(p3) Let's go to the first section. So for cosmology, what we measure are basically the cosmic microwave background temperature map and polarization maps which reflect the temperature anisotropies and polarization anisotropies.
This shows a full-sky temperature map from Planck. We can also have polarization maps like this.\theta is for temperature anisotropies, Q and U are stokes parameters for polarization anisotropies. In a word, almost all informaton is encoded in the maps.

(p4) The photons were from the last scattering suface where photons and free electrons decoupled. In the journal from the last scattering surface to here, the photons were distorted or say deflected by dark matter. Both temperature map and polarization maps are affected. This effect is called CMB lensing. The figure on the right is the difference of lensed and unlensed temperature map, you can see the temperature change. In mathematics, we can use this relation to express the CMB lensing and use a first order expansion. d is deflection field and \phi is lensing potential. According to the general relativity, it is a projection of gravtational potential along the comoving coordinate. Make sense?

(p5,6) Show unlensed map and lensed map

(p7) Lensing Reconstruction is very important in terms of finding out primordial gravitational waves. Maybe I will explain this later. It reflect the dark matter distribution, cross correlation with other dark matter surveys. It helps cosmological parameters constraints.
So we have to reconstruct CMB lensing. The process of getting CMB deflection maps and lensing potential from the lensed maps is called CMB lensing potential.

(p8) Usually we expand the anisotropies into fourier modes, we define the E-mode and B-mode like this. B-mode will play an important role in finding out premordial gravitational waves. Since in real experiment, we often do the expansion on small cut skies. We can neglect the curvature. The temperature map is a spin0 map and the polarization maps are spin2 maps (!!explain) 



