#+STARTUP: indent

Lensing reconstruction

* What is CMB lensing?
** explain cmb lensing

** cmb lensing and T,E,B modes
* Why lensing reconstruction?
** premordial GW
** dark matter
** delensing
** lensing cross-correlation
* How lensing reconstruction?
** lensing reconstruction
estimators
** lensing reconstruction on cut-sky
** lensing reconstruction on full-sly
*** show work
*** future plan on lensing reconstruction
* bias to cmb lensing reconstruction to reionization ksz
** reionization
** ksz
** explain how reionization ksz affects lensing reconstruction

* appendix


GW, tensor mode, polarization, EB mode
B mode sources
cmb tempature, polarization fields, fourier space, off-diagnal terms
noise model! noise unit!
optical depth
s/n 
* questions
- patchy tau
- optial depth
- reionization and ksz!!!
- lensing potential and convergence
- transfer functions
- matrix degree of freedom
- scales! units!


- cosmological parameters understanding
- lensing effect scale
- lensing effect on TT, TB, EB, order
- ell and angular scale and pixells
- B mode other contributions
- B mode other sources
- vector modes

- large scale, intermediate redshifts
- newlens alm and lensing map


- trispectrum
- reionization ksz affects lensing reconstruction physical image
- bias to lensing reconstruction from reionization ksz: temperature field and polarization field, scale?
- noise, map noise, noise level, N_pix in paperlaptop
- event horizon and gravitationl wave scales
- show results and preliminary conclusion

** 
? how curved sky better than flat sky; compare between them? 
? isotropic? unlensed CMB multipoles are assumed to be Gaussian and statistically isotropic(explain)
? name of l and alm

** 
? code source
? declining geometric kernel of CMB lensing at these high redshifs.

? compton scattering and Thomson scattering: Thomson scattering is the elastic scattering of electromagnetic radiation by a free charged particle, as described by classical electromagnetism. It is the low-energy limit of Compton scattering: the particle's kinetic energy and photon frequency do not change as a result of the scattering. This limit is valid as long as the photon energy is much smaller than the mass energy of the particle: , or equivalently, if the wavelength of the light is much greater than the Compton wavelength of the particle.

Reionization: At a redshift of about 10, hydrogen gets ionized again by the ultraviolet radiation of the first structures
kSZ: 



tSZ effect: CMB photons interact with electrons that have high energies due to their temperature
kSZ effect 
kSZ anisotropies: are produced in cosmological epochs during which there are large fluctuations in the electron density. ? (physical image)
``kSZ'' is used to refer to any blackbody temperature fluctuation arising from bulk motion integrated along the line of sight, including the Doppler effect.

? We refer to the Doppler effect as responsible for large-angle kSZ anisotropies.
? bulk velocity
? patchy reionization
? (B+C+E)
** 
To lowest order (in both optical depth and velocity), the kSZ effect produced only temperature anisotropies, not polarization anisotropies. 

late-time kSZ: are present in galaxies and clusters due to the non-linear growth of structure
reionization kSZ: fluctuations in the electron density field are due to fluctuations in the ionization fraction, are also expected to be correlated with the matter density field and hence with CMB lensing. 

? non-linear growth of structure
? seperation of ``late-time'' ksz and ``reionization ksz''
? addition of ``reionization ksz'' map and ``temperature'' map
? how do I tell the difference between ``late-time'' kSZ and ``reionization'' kSZ?

? model of reionization kSZ
? CMB unlensed and lensed simulations
? websky reionization kSZ simulation and late-time kSZ(Dr.Trac might ask about this)

CMB-S3 and CMB-S4 lensing 
for a Stage 4 CMB experiment
Their results have neglected the kSZ signal from reionization. 
kSZ sigunal due to fluctuations in the ionization fraction during reionization can bring a detectable bias(squeezed limit trispectrum)
I am working on simulating the bias to lensing reconstruction from reionization kSZ effect. 


As a member of both the Atacama Cosmology Telescope (ACT) and the
Simons Observatory (SO), I am actively involved in the research and
analysis projects in the collaborations. A short summary of each of my
involvements is listed below.

** 
Future:
So my work is mainly around lensing reconstruction.

1.Studying the bias to polarization reconstruction.
2.Primordial non-Gaussianity, collaborate with Yilun.

* tips
physical image!
search key words
order of magnitude!
report
make sure to understand every teminology in the report
show simulations
plans
* words
This applies to the simulated temperature full-sky map by now. My next setp would be improving its performance and applying polarization maps and then considering patchy maps.
* committe meeting
- lensing
- future plan related to lensing?
- full-sky and flat-sky comparison
- lensing reconstruction
** what?
** why?
** B mode topic
premodial B mode and tensor mode
** scalar-vector-tensor mode decomposition
** gravitational waves
** quadrupole and premordial B mode
** Q,U and E,B picture
- lecture notes in cosmology
- search E-mode and B-mode
- search stokes parameters and E-mode,B-mode in the "lectures notes in cosmology"
** 
* sources 
- yilun's committee meeting report
* report
* Arthur
show lensing maps, ksz maps
explain ksz simulations
add figures in the report
ksz lensing effect limit
* lecture
1.E B mode image
2.cosmological parameters constraints
3.real experiment, unlensed powerspec
4.names and year
5.angular scale//
6.ksz bias to polarization maps
7.lensing potential and noise

(p1) Hello, My name is Hongbo Cai. I am Dr.Kosowsky's student. This is my first committee meeting. Thank you for being a part of my committee and attending today's meeting. 

(p2) I have two topics to introduce: the first one is CMB lensing reconstruction on the curved sky; the second one is bias to lensing reconstruction from temperature anisotropies dut to reionization kSZ effect. So my work is around CMB lensing reconstruction. Part 1 is about how to do it. Part 2 is about investigating its bias.

(p3) When we taik about CMB, we are talk 3 maps. \theta for tempature anisotropies, q and u for linear polarization anisotropies. The CMB photons went from the last scattering surface where they decoupled with free electrons all the way to our telescope. We observe them and then we have the 3 maps. Here shows tempature anisotropies of the full sky from planck satellite.


(p4) What is between the last scattering surface and us? There is much dark matter. It can deflect the CMB photons and distort both the temperature map and polarization maps. This effect is called cmb lensing.


(p5,p6) Here shows a patch of unlensed CMB temperature map and also a lensed one. You can see the difference between them. 
(p7) And if you substract an unlensed map from a lensed map, you would see something like this.

(p7)
So how do we discribe CMB lensing in math? We use deflection field or lensing potential. The deflection map is the gradient of lensing potential. On this side, the maps without telda are lensed maps. On the other side, there are unlensed maps. and the deflection fields are here. 
According to General Relativity, we are able to express lensing potential as an integral of gravitationl potential over comoving distance from the last scattering surface and here. Make sense?


(p8)
And why we are interested in CMB lensing and why we need to reconstruct it?
There are several aspects.

1.It generates B mode which is a signature of PGW. So it is a confusion signal of PGW
2.It reflects dark matter distribution and we can do cross correlation with other dark matter surveys or galaxy surveys
3.It helps constrain cosmological parameters

The process of reconstructing lensing potential from lensed anisotropies is called lensing reconstruction.
Make sense?

(p9)
So how do we do lensing reconstruction? There are two situations: 
a.for small patch, we are safe to neglect the curvature of the sky and apply flat-sky CMB lensing reconstruction.
b.for large sky, we need to consider the curvature of the sky and apply curved-sky CMB lensing reconstruction.

(p10)
for flat sky, we apply fourier expansion, and get ... I didn't show the exact expression of the expansion. 

(p11)
for curved sky, we apply spherical harmonics decomposition and get the multiploe moments

as we can see, for both cases, lensing induces off-dignal terms of 2-pt correlation function, which means lensing changes the statistical property of the cmb maps. That's why we can take advange of this statistical property change to reconstruct CMB lensing. make sense?

In my work, I applied the curved sky estimators

(p12)
results,explain,simulation! Applied TT estimator and get noise curve of TT and EB estimators

(p13)
In the journal of CMB photons from last scattering surface to here, besides dark matter which induces lensing, there are also lots of free moving electrons with bulk velocity. These electrons scatter off CMB photons and change the CMB temperature map. This effect is called kSZ effect(kinematic ...)

(p14)
So for ksz effect, we should know that:1, 2,
equations, 
Since the observed temperature map includes ksz's contribution, if we apply lensing reconstruction pipeline, we get bias.

(p15)
there are two kind of kSZ effects: 1, ... due to the moving electrons of structures. 2. due to moving electrons ionized by the light emitted by the first structures. simulate the contributions on powerspec 

(p16)






(p10)
apply curved sky estimators

(p11)
show result. The performance is still limited especially for small scales.  This work is meant for impoving the existing lensing reconstruction pipeline. And more importantly, I learned useful CMB lensing reconstruction techiques from this project. These techniques are applied in the second part of work.

(p12)
show ksz image. 

(p13)
ksz math

(p14)
two contributions 

