#+STARTUP: indent

Lensing reconstruction

* What is CMB lensing?
** explain cmb lensing

** cmb lensing and T,E,B modes
* Why lensing reconstruction?
** premordial GW
** dark matter
** delensing
** lensing cross-correlation
* How lensing reconstruction?
** lensing reconstruction
estimators
** lensing reconstruction on cut-sky
** lensing reconstruction on full-sly
*** show work
*** future plan on lensing reconstruction
* bias to cmb lensing reconstruction to reionization ksz
** reionization
** ksz
** explain how reionization ksz affects lensing reconstruction

* appendix


GW, tensor mode, polarization, EB mode
B mode sources
cmb tempature, polarization fields, fourier space, off-diagnal terms
noise model! noise unit!
optical depth
s/n 
* questions
- patchy tau
- optial depth
- reionization and ksz!!!
- lensing potential and convergence
- transfer functions
- matrix degree of freedom
- scales! units!


- cosmological parameters understanding
- lensing effect scale
- lensing effect on TT, TB, EB, order
- ell and angular scale and pixells
- B mode other contributions
- B mode other sources
- vector modes

- large scale, intermediate redshifts
- newlens alm and lensing map


- trispectrum
- reionization ksz affects lensing reconstruction physical image
- bias to lensing reconstruction from reionization ksz: temperature field and polarization field, scale?
- noise, map noise, noise level, N_pix in paperlaptop
- event horizon and gravitationl wave scales
- show results and preliminary conclusion

** 
? how curved sky better than flat sky; compare between them? 
? isotropic? unlensed CMB multipoles are assumed to be Gaussian and statistically isotropic(explain)
? name of l and alm

** 
? code source
? declining geometric kernel of CMB lensing at these high redshifs.

? compton scattering and Thomson scattering: Thomson scattering is the elastic scattering of electromagnetic radiation by a free charged particle, as described by classical electromagnetism. It is the low-energy limit of Compton scattering: the particle's kinetic energy and photon frequency do not change as a result of the scattering. This limit is valid as long as the photon energy is much smaller than the mass energy of the particle: , or equivalently, if the wavelength of the light is much greater than the Compton wavelength of the particle.

Reionization: At a redshift of about 10, hydrogen gets ionized again by the ultraviolet radiation of the first structures
kSZ: 



tSZ effect: CMB photons interact with electrons that have high energies due to their temperature
kSZ effect 
kSZ anisotropies: are produced in cosmological epochs during which there are large fluctuations in the electron density. ? (physical image)
``kSZ'' is used to refer to any blackbody temperature fluctuation arising from bulk motion integrated along the line of sight, including the Doppler effect.

? We refer to the Doppler effect as responsible for large-angle kSZ anisotropies.
? bulk velocity
? patchy reionization
? (B+C+E)
** 
To lowest order (in both optical depth and velocity), the kSZ effect produced only temperature anisotropies, not polarization anisotropies. 

late-time kSZ: are present in galaxies and clusters due to the non-linear growth of structure
reionization kSZ: fluctuations in the electron density field are due to fluctuations in the ionization fraction, are also expected to be correlated with the matter density field and hence with CMB lensing. 

? non-linear growth of structure
? seperation of ``late-time'' ksz and ``reionization ksz''
? addition of ``reionization ksz'' map and ``temperature'' map
? how do I tell the difference between ``late-time'' kSZ and ``reionization'' kSZ?

? model of reionization kSZ
? CMB unlensed and lensed simulations
? websky reionization kSZ simulation and late-time kSZ(Dr.Trac might ask about this)

CMB-S3 and CMB-S4 lensing 
for a Stage 4 CMB experiment
Their results have neglected the kSZ signal from reionization. 
kSZ sigunal due to fluctuations in the ionization fraction during reionization can bring a detectable bias(squeezed limit trispectrum)
I am working on simulating the bias to lensing reconstruction from reionization kSZ effect. 


As a member of both the Atacama Cosmology Telescope (ACT) and the
Simons Observatory (SO), I am actively involved in the research and
analysis projects in the collaborations. A short summary of each of my
involvements is listed below.

** 
Future:
So my work is mainly around lensing reconstruction.

1.Studying the bias to polarization reconstruction.
2.Primordial non-Gaussianity, collaborate with Yilun.

* tips
physical image!
search key words
order of magnitude!
report
make sure to understand every teminology in the report
show simulations
plans
* words
This applies to the simulated temperature full-sky map by now. My next setp would be improving its performance and applying polarization maps and then considering patchy maps.
* committe meeting
- lensing
- future plan related to lensing?
- full-sky and flat-sky comparison
- lensing reconstruction
** what?
** why?
** B mode topic
premodial B mode and tensor mode
** scalar-vector-tensor mode decomposition
** gravitational waves
** quadrupole and premordial B mode
** Q,U and E,B picture
- lecture notes in cosmology
- search E-mode and B-mode
- search stokes parameters and E-mode,B-mode in the "lectures notes in cosmology"
** 
* sources 
- yilun's committee meeting report
* report
* Arthur
show lensing maps, ksz maps
explain ksz simulations
add figures in the report
ksz lensing effect limit
* lecture
Hello, 
